/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

import fr.solutec.dao.LogDao;
import fr.solutec.dao.ObjectifDao;
import fr.solutec.model.Log;
import fr.solutec.model.Objectif;
import fr.solutec.model.User;
import static fr.solutec.model.User.id_Actif;
import java.util.Calendar;

import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESIC
 */
public class FnMainPage extends javax.swing.JFrame {

    /**
     * Creates new form FnMainPage
     */
    public FnMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_fond_quotidien = new javax.swing.JPanel();
        Lb_Q1 = new javax.swing.JLabel();
        Lb_Q2 = new javax.swing.JLabel();
        Lb_Q3 = new javax.swing.JLabel();
        Lb_Q4 = new javax.swing.JLabel();
        Lb_Q5 = new javax.swing.JLabel();
        B_Objectif = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Obj = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Lb_Maindescr = new javax.swing.JLabel();
        B_Profil = new javax.swing.JButton();
        B_retour_acc = new javax.swing.JButton();
        B_Aide = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        T_der_con = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Lb_Q1.setText("            ");

        Lb_Q2.setText("         ");

        Lb_Q3.setText("           ");

        Lb_Q4.setText("           ");

        Lb_Q5.setText("          ");

        B_Objectif.setText("Gestion Objectifs");
        B_Objectif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ObjectifActionPerformed(evt);
            }
        });

        Table_Obj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Obj);

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mes Objectifs");

        javax.swing.GroupLayout P_fond_quotidienLayout = new javax.swing.GroupLayout(P_fond_quotidien);
        P_fond_quotidien.setLayout(P_fond_quotidienLayout);
        P_fond_quotidienLayout.setHorizontalGroup(
            P_fond_quotidienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                .addGroup(P_fond_quotidienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                        .addGap(729, 729, 729)
                        .addComponent(B_Objectif))
                    .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(P_fond_quotidienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_Q5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_fond_quotidienLayout.setVerticalGroup(
            P_fond_quotidienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Q1)
                .addGap(18, 18, 18)
                .addGroup(P_fond_quotidienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                        .addComponent(Lb_Q2)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Q3)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Q4)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_Q5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(B_Objectif)
                        .addGap(17, 17, 17))
                    .addGroup(P_fond_quotidienLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Lb_Maindescr.setBackground(new java.awt.Color(255, 0, 0));
        Lb_Maindescr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Lb_Maindescr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Maindescr.setText("Bienvenue");

        B_Profil.setText("Mon Profil");
        B_Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ProfilActionPerformed(evt);
            }
        });

        B_retour_acc.setText("Déconnexion");
        B_retour_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_retour_accActionPerformed(evt);
            }
        });

        B_Aide.setText("Aide");
        B_Aide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AideActionPerformed(evt);
            }
        });

        jLabel2.setText("Derniere connexion :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(P_fond_quotidien, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_Profil)
                                .addGap(112, 112, 112)
                                .addComponent(Lb_Maindescr, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_Aide)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_retour_acc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(T_der_con, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Maindescr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Profil)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_Aide)
                            .addComponent(B_retour_acc))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T_der_con, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(P_fond_quotidien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    // acces gestion objectif
    private void B_ObjectifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ObjectifActionPerformed
        
        
       FnObjectif Obj = new FnObjectif();
       this.setVisible(false);
       Obj.setVisible(true);
  
    }//GEN-LAST:event_B_ObjectifActionPerformed

    
    // Acces page d'aide
    private void B_AideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AideActionPerformed
        
       FnAide AID = new FnAide();
       
       AID.setVisible(true);
   
    }//GEN-LAST:event_B_AideActionPerformed

    
    
    // deconexion retour acceuil
    private void B_retour_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_retour_accActionPerformed
   
       User user1 = new User();
        user1.setId(id_Actif);
     
        Calendar currenttime = Calendar.getInstance();
        Date sqldate = new Date((currenttime.getTime()).getTime());
        
   
       Log log = new Log();
       log.setDate_Deconnexion(sqldate);
       log.setUser(user1);

       
 try {
            LogDao.insert_Log(log);
            
             User.id_Actif = 0;
             FnAcceuil Acc = new FnAcceuil();
             this.setVisible(false);
             Acc.setVisible(true);
  
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(rootPane, e.getMessage() + " Erreur");
           
       
       
    }//GEN-LAST:event_B_retour_accActionPerformed
    }
    
    
    
    // acces a la page profil
    private void B_ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ProfilActionPerformed
        
        
       FnProfil prof = new FnProfil();
       this.setVisible(false);
       prof.setVisible(true);
        
        
        
    }//GEN-LAST:event_B_ProfilActionPerformed

    
    
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

// afficher aide si première connexion


User user_Connecte = new User ();
user_Connecte.setId(id_Actif);

Log log_Connecte = new Log();
log_Connecte.setUser(user_Connecte);


try{

int i = LogDao.nombre_Connexion(log_Connecte);

if(i<=1){
FnAide Aide= new FnAide();
Aide.setVisible(true);
}


} catch (Exception e) {
JOptionPane.showInternalMessageDialog(rootPane, e.getMessage() + " Erreur");
}
        
        
        
        
        // afficher liste objectif
         DefaultTableModel model = new DefaultTableModel();
            model.addColumn("description");
            model.addColumn("Objectif");
            model.addColumn("Executé");
           
        
        
        try {
            List<Objectif> objectifs2 = ObjectifDao.getUserObjectif();
            
            for (Objectif objectif : objectifs2) {
                    model.addRow(new Object[] {
                    objectif.getDescription(),
                    objectif.getValeur_Max(),
                    objectif.getValeur_Actuelle(),
                
                });
                Table_Obj.setModel(model);
                
                
            }
            
        } catch (Exception e) { JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FnMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FnMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FnMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FnMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FnMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Aide;
    private javax.swing.JButton B_Objectif;
    private javax.swing.JButton B_Profil;
    private javax.swing.JButton B_retour_acc;
    private javax.swing.JLabel Lb_Maindescr;
    private javax.swing.JLabel Lb_Q1;
    private javax.swing.JLabel Lb_Q2;
    private javax.swing.JLabel Lb_Q3;
    private javax.swing.JLabel Lb_Q4;
    private javax.swing.JLabel Lb_Q5;
    private javax.swing.JPanel P_fond_quotidien;
    private javax.swing.JLabel T_der_con;
    private javax.swing.JTable Table_Obj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
